# Generated by Django 4.2.7 on 2023-11-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '__first__'),
        ('menu', '__first__'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество сета')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('number', models.CharField(max_length=15, verbose_name='Номер телефона клиента')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cafe.cafe', verbose_name='Кафе')),
                ('sets', models.ManyToManyField(through='reservation.OrderSets', to='menu.set', verbose_name='Заказы')),
                ('table', models.ManyToManyField(to='tables.table', verbose_name='Столы')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='ordersets',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sets', to='reservation.reservation', verbose_name='Бронь'),
        ),
        migrations.AddField(
            model_name='ordersets',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.set', verbose_name='Сет'),
        ),
    ]
