# Generated by Django 4.2.7 on 2023-11-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0001_initial'),
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество сета')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('name', models.CharField(max_length=256, verbose_name='Имя клиента')),
                ('number', models.CharField(max_length=15, verbose_name='Номер телефона клиента')),
                ('status', models.CharField(choices=[('booked', 'Забронировано'), ('cancelled', 'Отменено')], default='booked', max_length=256, verbose_name='Статус брони')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cafe.cafe', verbose_name='Кафе')),
                ('sets', models.ManyToManyField(through='reservation.OrderSets', to='menu.set', verbose_name='Заказы')),
                ('table', models.ManyToManyField(to='tables.table', verbose_name='Столы')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservations', to='reservation.reservation', verbose_name='Бронь')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservations', to='tables.table', verbose_name='Забронированный стол')),
            ],
            options={
                'verbose_name': 'Бронь стола',
                'verbose_name_plural': 'Брони столов',
            },
        ),
        migrations.AddField(
            model_name='ordersets',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_sets', to='reservation.reservation', verbose_name='Бронь'),
        ),
        migrations.AddField(
            model_name='ordersets',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sets', to='menu.set'),
        ),
        migrations.AddConstraint(
            model_name='ordersets',
            constraint=models.UniqueConstraint(fields=('reservation', 'sets'), name='unique_reservation_sets'),
        ),
    ]
