# Generated by Django 4.2.7 on 2023-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сета')),
                ('description', models.CharField(max_length=200, verbose_name='Описание сета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена сета')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество сетов')),
            ],
            options={
                'verbose_name': 'Сет',
                'verbose_name_plural': 'Сеты',
                'ordering': ('price', 'name'),
            },
        ),
    ]
