# Generated by Django 4.2.7 on 2023-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdish',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество блюд в сете'),
        ),
    ]
