# Generated by Django 4.2.7 on 2023-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_setdish_quantity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='setdish',
            name='unique_set_dish',
        ),
        migrations.AddConstraint(
            model_name='setdish',
            constraint=models.UniqueConstraint(fields=('set', 'dish', 'quantity'), name='unique_set_dish_quantity'),
        ),
    ]
