# Generated by Django 4.2.7 on 2023-11-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_component_set_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='SetDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество блюд')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish')),
            ],
        ),
        migrations.RemoveField(
            model_name='set',
            name='components',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.AddField(
            model_name='setdish',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.set'),
        ),
        migrations.AddField(
            model_name='set',
            name='dishes',
            field=models.ManyToManyField(blank=True, through='menu.SetDish', to='menu.dish', verbose_name='Блюда'),
        ),
    ]
